# Generated by Django 5.2.17 on 2026-08-11 15:59

import django.core.validators
import django.db.models.deletion
import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('iban_last_four', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#64748b', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#0f766e', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('bank_statement', 'Kontoauszug'), ('invoice', 'Rechnung'), ('receipt', 'Kassenbeleg'), ('other', 'Sonstiges')], max_length=30)),
                ('file', models.FileField(upload_to=ledger.models.document_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('document_date', models.DateField(blank=True, db_index=True, null=True)),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('extracted_text', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.category')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Zugeordnet'), ('payer', 'Zahler/in'), ('beneficiary', 'Begünstigte Person')], default='owner', max_length=20)),
                ('share_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.document')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.person')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='people',
            field=models.ManyToManyField(related_name='documents', through='ledger.DocumentPerson', to='ledger.person'),
        ),
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parser_name', models.CharField(blank=True, max_length=100)),
                ('parser_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('uploaded', 'Hochgeladen'), ('processing', 'Wird verarbeitet'), ('review', 'Prüfung erforderlich'), ('imported', 'Importiert'), ('failed', 'Fehlgeschlagen')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ledger.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='ledger.tag'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_fingerprint', models.CharField(max_length=64, unique=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.category')),
                ('documents', models.ManyToManyField(blank=True, related_name='transactions', to='ledger.document')),
                ('people', models.ManyToManyField(blank=True, related_name='transactions', to='ledger.person')),
                ('statement_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.statementimport')),
                ('tags', models.ManyToManyField(blank=True, related_name='transactions', to='ledger.tag')),
            ],
            options={
                'ordering': ['-booking_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentperson',
            constraint=models.UniqueConstraint(fields=('document', 'person', 'role'), name='unique_document_person_role'),
        ),
    ]
