# Generated by Django 5.2.17 on 2026-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
