# Generated by Django 5.2.17 on 2026-08-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transaction_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('match_text', models.CharField(max_length=255, unique=True)),
                ('auto_apply', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('times_applied', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.category')),
                ('people', models.ManyToManyField(blank=True, related_name='categorization_rules', to='ledger.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='categorization_rules', to='ledger.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
