# Generated by Django 5.2.17 on 2026-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_category_active_tag_active_categorizationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'Wird verarbeitet'), ('review', 'Prüfung erforderlich'), ('processed', 'Verarbeitet'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20),
        ),
    ]
