# Generated by Django 5.2.17 on 2026-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_mark_imported_statements_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementimport',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='reconciliation_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='reconciliation_status',
            field=models.CharField(choices=[('unavailable', 'Nicht prüfbar'), ('balanced', 'Ausgeglichen'), ('mismatch', 'Abweichung')], default='unavailable', max_length=20),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='transaction_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
