# Generated by Django 5.2.17 on 2026-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_statementimport_closing_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorizationrule',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Höhere Werte werden zuerst ausgewertet.'),
        ),
    ]
