# Generated by Django 5.2.17 on 2026-08-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_categorizationrule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=993)),
                ('security', models.CharField(choices=[('ssl', 'SSL/TLS'), ('starttls', 'STARTTLS')], default='ssl', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('encrypted_password', models.TextField(blank=True, editable=False)),
                ('folder', models.CharField(default='INBOX', max_length=255)),
                ('allowed_senders', models.TextField(blank=True, help_text='Eine Adresse pro Zeile. Leer bedeutet: alle Absender akzeptieren.')),
                ('poll_interval_minutes', models.PositiveIntegerField(default=5)),
                ('mark_as_read', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailImportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox_uid', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=998)),
                ('sender', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.emailimportconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('config', 'mailbox_uid'), name='unique_email_import_uid')],
            },
        ),
    ]
